apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: powerdns
  namespace: infra
spec:
  routes:
  - kind: Rule
    match: HostRegexp(`{host:^powerdns.*}`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: powerdns-service-admin
      namespace: infra
      port: 9191
