---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: powerdns
  namespace: infra
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: powerdns
  chart:
    git: https://github.com/jarretlavallee/helm-powerdns
    ref: feat/master/updates
    path: powerdns
  values:
    powerdns:
      domain: home.lab
      default_soa_name: ns1.home.lab
      service:
        dns:
          loadBalancerIP: 192.168.5.90
          annotations:
            external-dns.alpha.kubernetes.io/hostname: ns1.home.lab
    powerdnsadmin:
      service:
        type: ClusterIP
        annotations:
          external-dns.alpha.kubernetes.io/hostname: powerdns.home.lab
          external-dns.alpha.kubernetes.io/target: traefik.home.lab
