---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cd4pe
  namespace: puppet
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: cd4pe
  chart:
    repository: https://jarretlavallee.github.io/helm-charts/
    name: cd4pe
    version: 0.1.1
  values:
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: cd4pe.home.lab
    dbPasswordSecret: cd4pe-postgresql-secret
    dbPasswordSecretKey: postgresql-password
    uniqueIdSecret: cd4pe-postgresql-secret
    uniqueIdSecretKey: uniqueId
    postgresql:
      existingSecret: cd4pe-postgresql-secret
    sidecars:
      - name: smee
        image: deltaprojects/smee-client
        args: ["--port", "8000", "--path", "/gitlab/push", "--url", "https://smee.io/paljfWgJ3yRfmmr"]
