---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cd4pe
  namespace: puppet
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: cd4pe
  chart:
    repository: https://jarretlavallee.github.io/helm-charts/
    name: cd4pe
    version: 0.1.0
  values:
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: cd4pe.home.lab
