---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ghost
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: ghost
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: ghost
    version: 10.0.5
  values:
    service:
      #      type: ClusterIP
      annotations:
        external-dns.alpha.kubernetes.io/hostname: ghost.home.lab
        #        external-dns.alpha.kubernetes.io/target: traefik.home.lab
        #        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    ghostHost: ghost.home.lab
    ghostPort: 80
    ghostProtocol: http
    ghostPassword: homelab123
    mariadb:
      db:
        password: homelab123
    timezone: "America/Denver"
    ingress:
      enabled: true
      hosts:
        - name: ghost.home.lab
