---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kured
  namespace: maint
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: reloader
  chart:
    repository: https://stakater.github.io/stakater-charts
    name: reloader
    version: v0.0.58
