{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "external-dns-cloudflare",
    "namespace": "infra",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "external-dns-cloudflare",
        "namespace": "infra",
        "creationTimestamp": null,
        "labels": {
          "app.kubernetes.io/instance": "external-dns",
          "app.kubernetes.io/managed-by": "Helm",
          "app.kubernetes.io/name": "external-dns",
          "helm.sh/chart": "external-dns-2.21.2"
        },
        "managedFields": [
          {
            "manager": "Go-http-client",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2020-04-24T23:40:34Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {"f:data":{".":{},"f:cloudflare_api_token":{}},"f:metadata":{"f:labels":{".":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:helm.sh/chart":{}}},"f:type":{}}
          }
        ]
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "cloudflare_api_token": "AgA8pX9esLDy7rATNzRk0LXol4acp+qchIxWA9rDvgG2SJ+1UPafSzJL5Ts71zIErekjyT2Vr89EMQy+4C73NvGyhyPOeNxmYLwMN61uwxTqA9f5PrG8Wlqof2GUKQoJslloxyiO2ulwwmDeslABgi4VX337oyCU8jktHldDVnXkuXutWXq02r/FaIq73yfzGF05N2DnBMzrjDIkIYvp76EAmBMXT5sOIigOBowyLyGwRs5HAtQcXuNhRJ/SqkDw2hAZF+Z6zYfm+NMQYaB5pLmp7kqz0vpBsQbbWs1Crdkzgcr6NoxmA+lBqcMNDnXogg2eAaH7g4LZhqdubZmQyVnqW+WnpfpH9HyOERzoD31Cuul+eAoSXr6iRJtRAdoAEpe2O08XasEvOCB6OXLjznolu/TVcQzDnyxaPz/E/Sl4bbmxk/7u/Xn6xk2k2aCOotpu99lcskKdAQqzWIPkmgASWCa9kWw4EgtD8dFI3OxZ/HsKNcCK9zeNR63vgPkONxYxN/QmS8fJiGSXDMmbQUmEXEXv3gfC9WDHyEtSuOpJ2WkD2JRlHmH9hwu9JHfs2VG/D2PFU4HA2ugAiWNr3cI0KEM+v/2iCjZoVXSbajUVZN+lpNVigH7EF/z5GTnv98UluBgTxLJppJ7zNTs6O8oD8P4CpYeeM2HacSGfWByag2SjtEkMlNvvL/N3yZ63rE7HgKULNBSS2F6gYt9ScCDt9W7fTJXJ9JuBL8hJPPJHs+jiN7NgQeq4"
    }
  }
}
