---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: grafana
    version: 5.0.13
  values:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: grafana.hubnut.ga
        external-dns.alpha.kubernetes.io/target: traefik.hubnut.ga
    persistence:
      storageClassName: standard
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
      dashboards:
        enabled: true
        label: grafana_dashboard
