# dashboard.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  routes:
    - match: HostRegexp(`{host:^grafana.*}`)
      kind: Rule
      services:
        - name: grafana
          kind: Service
          port: 80
          scheme: http
