---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: fluent-bit
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: fluent-bit
    version: 2.8.13
  values:
    backend:
      type: es
      es:
        host: elastic-es-http
        port: 9200
        http_user: elastic
        http_passwd_secret: elastic-es-elastic-user
        http_passwd_secret_key: elastic
        tls: on
        tls_verify: off
