---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: wordpress
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: wordpress
    version: 9.3.3
  values:
    service:
      type: ClusterIP
    wordpressPassword: homelab
    mariadb:
      db:
        password: homelab
    timezone: "America/Denver"
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: wordpress.home.lab
        external-dns.alpha.kubernetes.io/target: traefik.home.lab
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      hostname: wordpress.home.lab
