---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-web
  namespace: flux
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: flux-web
  chart:
    git: git@github.com:flux-web/flux-web.git
    path: chart/flux-web
    ref: master
  values:
    frontend:
        env:
          API_EXTERNAL_URL: //flux.home.lab/api/v1
          WS_URL: wss://flux.home.lab/ws/v1
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: flux.home.lab
        external-dns.alpha.kubernetes.io/target: traefik.home.lab
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      hosts:
        - host: flux.home.lab
          paths:
            - frontend: /
            - backend: /api
            - backend: /ws
