---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: goldilocks
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://charts.fairwinds.com/stable
    name: goldilocks
    version: 2.3.1
  values:
    installVPA: true
    dashboard:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: goldilocks.home.lab
          external-dns.alpha.kubernetes.io/target: traefik.home.lab
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        hosts:
          - host: goldilocks.home.lab
            paths:
              - /
