---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-ui
  namespace: flux
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: flux-ui
  chart:
    git: https://github.com/sureshamk/flux-ui
    path: flux-ui
    ref: master
  values:
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: flux.home.lab
        external-dns.alpha.kubernetes.io/target: traefik.home.lab
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      hosts:
        - host: flux.home.lab
          paths:
            -  /
