---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: metrics-server
  chart:
    repository: https://charts.helm.sh/stable/
    name: metrics-server
    version: 2.11.1
  values:
    hostNetwork:
      enabled: true
    args:
      - --v=2
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
