---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus
    version: 13.0.2
  values:
    server:
      ingress:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: prometheus.home.lab
          external-dns.alpha.kubernetes.io/target: traefik.home.lab
      persistentVolume:
        storageClass: nfs
