---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: prometheus
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus
    version: 11.1.2
  values:
    server:
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: prometheus.hubnut.ga
          external-dns.alpha.kubernetes.io/target: traefik.hubnut.ga
      persistentVolume:
        storageClass: nfs
