---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-unifi
  namespace: infra
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
