---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: infra
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: unifi
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: unifi
    version: 0.7.0
  values:
    image:
      tag: latest
      pullPolicy: Always
    persistence:
      existingClaim: data-unifi
    guiService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.5.89
      annotations:
        external-dns.alpha.kubernetes.io/hostname: unifi.home.lab
        metallb.universe.tf/allow-shared-ip: "unifi"
    controllerService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.5.89
      annotations:
        metallb.universe.tf/allow-shared-ip: "unifi"
    stunService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.5.89
      annotations:
        metallb.universe.tf/allow-shared-ip: "unifi"
    discoveryService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.5.89
      annotations:
        metallb.universe.tf/allow-shared-ip: "unifi"
