---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: infra
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: unifi
  chart:
    repository: https://k8s-at-home.com/charts
    name: unifi
    version: 1.5.2
  values:
    persistence:
      storageClass: nfs
    guiService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.5.89
      annotations:
        external-dns.alpha.kubernetes.io/hostname: unifi.home.lab
        metallb.universe.tf/allow-shared-ip: "unifi"
    controllerService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.5.89
      annotations:
        metallb.universe.tf/allow-shared-ip: "unifi"
    stunService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.5.89
      annotations:
        metallb.universe.tf/allow-shared-ip: "unifi"
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 192.168.5.89
      annotations:
        metallb.universe.tf/allow-shared-ip: "unifi"
    syslogService:
      type: LoadBalancer
      loadBalancerIP: 192.168.5.89
      annotations:
        metallb.universe.tf/allow-shared-ip: "unifi"
    speedtestService:
      type: LoadBalancer
      loadBalancerIP: 192.168.5.89
      annotations:
        metallb.universe.tf/allow-shared-ip: "unifi"
    resources:
      limits:
        memory: 750Mi
      requests:
        cpu: 49m
        memory: 640Mi
