---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: metallb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.12.0
  values:
    prometheus:
      scrapeAnnotations: true
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.5.80-192.168.5.99
