---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: metallb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: stable/metallb
    version: 0.12.0
  values:
    address-pools:
      - name: default
        protocol: layer2
        addresses: 192.168.5.80-192.168.5.90
