---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: longhorn
  chart:
    git: https://github.com/longhorn/longhorn
    path: chart
    ref: master
  values:
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: longhorn.home.lab
        external-dns.alpha.kubernetes.io/target: traefik.home.lab
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      host: longhorn.home.lab
    persistence:
      defaultClass: false
    defaultSettings:
      backupTarget: nfs://freenas.home.lab:/mnt/data/backups
