---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: infra
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: traefik
  chart:
    repository: https://containous.github.io/traefik-helm-chart
    name: traefik
    version: 8.1.2
  values:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: traefik.home.lab
    additionalArguments:
      - "--api.insecure=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus=true"
