name: Test

on: [push, pull_request]

jobs:
  hrval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Helm Releases in all namespaces
        uses: stefanprodan/hrval-action@v3.2.0
        with:
          helmRelease: ./
          helmVersion: v3
